# Generated by Django 4.2.2 on 2023-10-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplane',
            name='data',
        ),
    ]
