# Generated by Django 4.2.2 on 2023-10-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plane', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plane',
            old_name='data',
            new_name='compile',
        ),
    ]
